Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "openjdk-java8-maven"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "site.yml"
  end
end
