Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "mwsu-schedule-dev"
  config.vm.provision "shell", path: "flask-env.sh"

  config.vm.network "forwarded_port", guest: 3000, host: 3000, id: "schedule-search", protocol: "tcp", auto_correct: true
  config.vm.network "forwarded_port", guest: 5000, host: 5000, id: "schedule-api", protocol: "tcp", auto_correct: true
end
