Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "ansible-ctrl-dev"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "site.yml"
  end
end
