Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "flask-dev"
  config.vm.provision "shell", path: "flask-env.sh"

  
  config.vm.network "forwarded_port", guest: 3000, host: 3000, id: "flask", protocol: "tcp", auto_correct: true
end
